bim_data_format:
  include_geometry: false
prompt_framing_style:
  german: false
prompt_reasoning_strategy:
  chain_of_thought: false
  extract_then_reason: false
  iterative_self_refinement: true
prompt_contextualization:
  include_examples: true
