# === Database Settings ===
database_config:

  # Which database should be used for the material matching & LCA calculation?
  database: "kbob"



# === IfcBuilding Element Data Filtering ===
filter_config:

  # Only include the psets in the list config/step_01_data_extraction/pset_selection.py (can be altered!)
  # This minimizes token usage alot, but the list of psets is very tailored (specific) to the sampeled IFC models!
  # If there is no prior knowledge of exact pset key names (or relevancy for inference), set to false
  use_pset_filter: true

  # Path to the pset key file if use_pset_filter: true (can add and remove keys!)
  pset_key_file: "configs/templates/pset_selection.py"

  # Choose either "custom" or "preset". Custom allows for user-based configuration of what should be included.
  mode: "preset"

  # Choose data Level of Information (LOI) preset. Used only if mode is "preset"; must be one of: low_LOI, medium_LOI, high_LOI
  preset: "include_geometry_data" # or "discard_geometry_data"

  # Used only if mode is "custom"; this is the folder that contains both customizable YAML files
  custom_path: "config/step_01_data_extraction/filter_custom"

  # Used to remove "empty" or "unknown" key-value pairs (minimizes tokens). Set to "false" to maintain.
  remove_empty_values: true

  # Reordering of keys. Maintain the name and the indent, only change order!
  # LLMs can be sensitive to the order of data. Especially data in the "middle" tends to get lost, according to some academic literature.
  # The presets below are a good basis (i.e., you can also just leave as-is)

  # Key order for the "IfcBuildingElement" data sheets
  element_key_order:
    - Element Metadata
    - Element Material Data
    - Element Geometry Data
    - Element Property Sets
    - Element Relationships
    - Element Location
    - CompilationGroupID

  # Key order for the dissected layer sheets of multi-layer elements
  target_layer_key_order:
    - Target Layer of Material Inference
    - Building Element Context
    - CompilationGroupID

  # Key order for the dissected layer sheets of multi-layer elements
  building_element_context_key_order:
    - Element Metadata
    - Other Material Layers
    - Layer Set Metadata
    - Element Geometry Data
    - Element Property Sets
    - Element Relationships
    - Element Location



